school/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :students
  resources :teachers

  resources :courses do
    resources :assignments
    resources :quizzes
  end

end

school/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course
end

school/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student

  has_many :assignments, dependent: :destroy
  has_many :quizzes, dependent: :destroy
end

school/app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :courses
end

school/app/models/student.rb
class Student < ActiveRecord::Base
  has_many :courses
  has_many :teachers, through: :courses
  
end

school/app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :courses
  has_many :students, through: :courses

end

school/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

school/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
  	@assignments = Assignment.where(course_id: params[:course_id])
  end

  def show
  	@assignment = Assignment.find(params[:id])
  end

  def new
  	@assignment = Assignment.new(course_id: params[:course_id])
  end

  def create
  	@assignment = Assignment.new(assignment_params)
  	if @assignment.save
  		redirect_to course_assignments_path(params[:course_id])
  	else
  		render :new
  	end
  end

  def edit
  	@assignment = Assignment.find(params[:id])
  end

  def update
  	@assignment = Assignment.find(params[:id])
  	if @assignment.update(assignment_params)
  		redirect_to course_assignments_path(params[:course_id])
  	else
  		render :edit
  	end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to course_assignments_path(params[:course_id])
  end

private

	def assignment_params
		params.require(:assignment).permit(:title, :course_id)
	end

end

school/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
  	@courses = Course.all
  end

  def show
  	@course = Course.find(params[:id])
  end

  def new
  	@course = Course.new
  end

  def create
  	@course = Course.new(course_params)
  	if @course.save
  		redirect_to courses_path
  	else
  		render :new
  	end
  end

  def edit
  	@course = Course.find(params[:id])
  end

  def update
  	@course = Course.find(params[:id])
  	if @course.update(course_params)
  		redirect_to courses_path
  	else
  		render :edit
  	end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

private

	def course_params
		params.require(:course).permit(:title)
	end

end

school/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
  	@quizzes = Quiz.where(course_id: params[:course_id])
  end

  def show
  	@quiz = Quiz.find(params[:id])
  end

  def new
  	@quiz = Quiz.new(course_id: params[:course_id])
  end

  def create
  	@quiz = Quiz.new(quiz_params)
  	if @quiz.save
  		redirect_to course_quizzes_path(params[:course_id])
  	else
  		render :new
  	end
  end

  def edit
  	@quiz = Quiz.find(params[:id])
  end

  def update
  	@quiz = Quiz.find(params[:id])
  	if @quiz.update(quiz_params)
  		redirect_to course_quizzes_path(params[:course_id])
  	else
  		render :edit
  	end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to course_quizzes_path(params[:course_id])
  end

private

	def quiz_params
		params.require(:quiz).permit(:title, :course_id)
	end

end

school/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

school/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
  	@students = Student.all
  end

  def show
  	@student = Student.find(params[:id])
  end

  def new
  	@student = Student.new
  end

  def create
  	@student = Student.new(student_params)
  	if @student.save
  		redirect_to students_path
  	else
  		render :new
  	end
  end

  def edit
  	@student = Student.find(params[:id])
  end

  def update
  	@student = Student.find(params[:id])
  	if @student.update(student_params)
  		redirect_to students_path
  	else
  		render :edit
  	end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

private

	def student_params
		params.require(:student).permit(:first_name, :last_name)
	end

end

school/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
  	@teachers = Teacher.all
  end

  def show
  	@teacher = Teacher.find(params[:id])
  end

  def new
  	@teacher = Teacher.new
  end

  def create
  	@teacher = Teacher.new(teacher_params)
  	if @teacher.save
  		redirect_to teachers_path
  	else
  		render :new
  	end
  end

  def edit
  	@teacher = Teacher.find(params[:id])
  end

  def update
  	@teacher = Teacher.find(params[:id])
  	if @teacher.update(teacher_params)
  		redirect_to teachers_path
  	else
  		render :edit
  	end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to teachers_path
  end

private

	def teacher_params
		params.require(:teacher).permit(:first_name, :last_name)
	end

end

school/app/helpers/application_helper.rb
module ApplicationHelper
end

school/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

school/app/helpers/courses_helper.rb
module CoursesHelper
end

school/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

school/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

school/app/helpers/students_helper.rb
module StudentsHelper
end

school/app/helpers/teachers_helper.rb
module TeachersHelper
end

school/app/views/assignments/_form.html.erb
<% if params[:action] == 'new'
     go_to = course_assignments_path(params[:course_id])
  else
    go_to = course_assignment_path(params[:course_id], params[:id])
  end %>



<%= form_for @assignment, url: go_to do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.hidden_field :course_id, value: params[:course_id] %>

  <%= f.submit 'Submit' %>
<% end %>

school/app/views/assignments/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

school/app/views/assignments/index.html.erb
<h1>Assignments</h1>
<%= link_to 'New Assignment', new_course_assignment_path %>

<% @assignments.each do |assignment| %>
  <h3><%= assignment.title %></h3>
  <%= link_to 'Assignment Details', course_assignment_path(assignment.course_id, assignment) %>
<% end %>

school/app/views/assignments/new.html.erb
<h1>New Assignment</h1>
<%= render 'form' %>

school/app/views/assignments/show.html.erb
<h1><%= @assignment.title %></h1>

<%= link_to 'Back', course_assignments_path(@assignment.course_id) %>
<%= link_to 'Edit', edit_course_assignment_path(@assignment.course_id, @assignment) %>
<%= link_to 'Delete', course_assignment_path(@assignment.course_id, @assignment), method: :delete %>

school/app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit 'Submit'%>
 <% end %>

school/app/views/courses/edit.html.erb
<h1>Edit Course Details</h1>
<%= render 'form' %>

school/app/views/courses/index.html.erb
<h1>Courses</h1>
<%= link_to 'New Course', new_course_path %>

<% @courses.each do |course| %>
  <h3><%= course.title %></h3>
  <%= link_to 'Course Details', course_path(course) %>
<% end %>

school/app/views/courses/new.html.erb
<h1>Add a New Course</h1>
<%= render 'form' %>
<%= link_to 'Back', courses_path %>

school/app/views/courses/show.html.erb
<h1>Course Details</h1>
<h3><%= @course.title %></h3>
<%= link_to 'Back', courses_path %>
<%= link_to 'Edit', edit_course_path(@course)  %>
<%= link_to 'Delete', @course, method: :delete %>
<%= link_to 'Quizzes', course_quizzes_path(@course) %>
<%= link_to 'Assignments', course_assignments_path(@course) %>

school/app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Teachers', teachers_path %>
<%= link_to 'Students', students_path %>
<%= link_to 'Courses', courses_path %>

school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>School</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

school/app/views/quizzes/_form.html.erb
<% if params[:action] == 'new'
     go_to = course_quizzes_path(params[:course_id])
  else
    go_to = course_quiz_path(params[:course_id], params[:id])
  end %>



<%= form_for @quiz, url: go_to do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.hidden_field :course_id, value: params[:course_id] %>

  <%= f.submit 'Submit' %>
<% end %>

school/app/views/quizzes/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

school/app/views/quizzes/index.html.erb
<h1>Quizzes</h1>
<%= link_to 'New Quiz', new_course_quiz_path %>
<%= link_to 'Back', course_path(params[:course_id]) %>


<% @quizzes.each do |quiz| %>

  <h3><%= quiz.title %></h3>
  <%= link_to 'Details', course_quiz_path(quiz.course_id, quiz) %>

<% end %>

school/app/views/quizzes/new.html.erb
<h1>New Quiz</h1>
<%= render 'form' %>

school/app/views/quizzes/show.html.erb
<h1><%= @quiz.title %></h1>

<%= link_to 'Back', course_quizzes_path(@quiz.course_id) %>
<%= link_to 'Edit', edit_course_quiz_path(@quiz.course_id, @quiz) %>
<%= link_to 'Delete', course_quiz_path(@quiz.course_id, @quiz), method: :delete %>

school/app/views/static_pages/home.html.erb
<h1>Home Page</h1>

school/app/views/students/_student_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :first_name %>: 
  <%= f.text_field :first_name %>

  <%= f.label :last_name %> 
  <%= f.text_field :last_name %>

  <%= f.submit %>
<% end %>

school/app/views/students/edit.html.erb
<h1>Students#edit</h1>

<%= render 'student_form' %>

school/app/views/students/index.html.erb
<h1>Students</h1>
<%= link_to 'new', new_student_path %>


<% @students.each do |student| %>
<p><%= student.first_name %>
<%= student.last_name %></p>
<%= link_to 'show', student_path(student) %>
<%= link_to 'edit', edit_student_path(student) %>
<%= link_to 'delete', student, method: :delete %>
<% end %>

school/app/views/students/new.html.erb
<h1>Students#new</h1>

<%= render 'student_form' %>

school/app/views/students/show.html.erb
<h1>Students#show</h1>


<p><%= @student.first_name %>
<%= @student.last_name %></p>
<%= link_to 'show', student_path(student) %>
<%= link_to 'edit', edit_student_path(student) %>
<%= link_to 'delete', student, method: :destroy %>

school/app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>

<h1> New Teacher </h1>
<%= form_for @teacher do |f| %>
  <%= f.label :first_name %> 
  <%= f.text_field :first_name %>

  <%= f.label :last_name %> 
  <%= f.text_field :last_name %>

  <%= f.submit %>
<% end %>

school/app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<h1> Teachers </h1>
  <%= link_to 'New Teacher', new_teacher_path %> 
<% @teachers.each do |teacher| %>
  <h2><%= teacher.first_name %></h2>
  <h3><%= teacher.last_name %></h3>
  <%= link_to 'Show Teacher', teacher_path(teacher)%>
  <%= link_to 'Edit Teacher', edit_teacher_path(teacher) %>
  <%= link_to 'Delete Teacher', teacher, method: :delete %>
<% end %>

school/app/views/teachers/new.html.erb
<h1>Teachers#new</h1>

<h1> New Teacher </h1>
<%= form_for @teacher do |f| %>
  <%= f.label :first_name %> 
  <%= f.text_field :first_name %>

  <%= f.label :last_name %> 
  <%= f.text_field :last_name %>

  <%= f.submit %>
<% end %>

school/app/views/teachers/show.html.erb
<h1>Teachers#show</h1>
<%= @teacher.first_name %>
<%= @teacher.last_name %>
<br><br>
<%= link_to 'Back to Teachers', teachers_path %>